/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 14 14:40:13 EDT 2018
 */

package edu.ncsu.csc326.coffeemaker;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = false, useJEE = true) 
public class RecipeBook_ESTest extends RecipeBook_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe recipe0 = new Recipe();
      recipe0.setName("V");
      recipeBook0.addRecipe(recipe0);
      recipeBook0.editRecipe(0, recipe0);
      assertEquals("", recipe0.getName());
      assertEquals("", recipe0.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe recipe0 = new Recipe();
      recipeBook0.addRecipe(recipe0);
      String string0 = recipeBook0.deleteRecipe(0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe recipe0 = new Recipe();
      recipeBook0.addRecipe(recipe0);
      // Undeclared exception!
      try { 
        recipeBook0.editRecipe(0, (Recipe) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.ncsu.csc326.coffeemaker.RecipeBook", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe recipe0 = new Recipe();
      // Undeclared exception!
      try { 
        recipeBook0.editRecipe(4, recipe0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         verifyException("edu.ncsu.csc326.coffeemaker.RecipeBook", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      // Undeclared exception!
      try { 
        recipeBook0.deleteRecipe((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("edu.ncsu.csc326.coffeemaker.RecipeBook", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      // Undeclared exception!
      try { 
        recipeBook0.addRecipe((Recipe) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.ncsu.csc326.coffeemaker.RecipeBook", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe recipe0 = new Recipe();
      recipeBook0.addRecipe(recipe0);
      String string0 = recipeBook0.editRecipe(0, recipe0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe recipe0 = new Recipe();
      String string0 = recipeBook0.editRecipe(0, recipe0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      String string0 = recipeBook0.deleteRecipe(0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe recipe0 = new Recipe();
      recipe0.setName("B");
      boolean boolean0 = recipeBook0.addRecipe(recipe0);
      assertTrue(boolean0);
      
      String string0 = recipeBook0.deleteRecipe(0);
      assertNotNull(string0);
      
      boolean boolean1 = recipeBook0.addRecipe(recipe0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe recipe0 = new Recipe();
      boolean boolean0 = recipeBook0.addRecipe(recipe0);
      boolean boolean1 = recipeBook0.addRecipe(recipe0);
      assertFalse(boolean1);
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      RecipeBook recipeBook0 = new RecipeBook();
      Recipe[] recipeArray0 = recipeBook0.getRecipes();
      assertEquals(4, recipeArray0.length);
  }
}
