/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 14 17:00:33 GMT 2018
 */

package familytree.model;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = false, useJEE = true) 
public class Person_ESTest extends Person_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(79, person0.getId());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar();
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=1539536421048,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2018,MONTH=9,WEEK_OF_YEAR=41,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=287,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=0,SECOND=21,MILLISECOND=48,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      
      person0.setDateOfDeath(gregorianCalendar0);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(79, person0.getId());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=1539536421048,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2018,MONTH=9,WEEK_OF_YEAR=41,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=287,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=0,SECOND=21,MILLISECOND=48,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      
      GregorianCalendar gregorianCalendar1 = person0.getDateOfDeath();
      //  // Unstable assertion: assertNotNull(gregorianCalendar1);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(79, person0.getId());
      //  // Unstable assertion: assertTrue(gregorianCalendar1.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar1.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=1539536421048,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2018,MONTH=9,WEEK_OF_YEAR=41,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=287,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=0,SECOND=21,MILLISECOND=48,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar1.toString());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar1.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar1.equals((Object)gregorianCalendar0));
      //  // Unstable assertion: assertNotSame(gregorianCalendar1, gregorianCalendar0);
      
      gregorianCalendar1.setTimeInMillis(0L);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(79, person0.getId());
      //  // Unstable assertion: assertTrue(gregorianCalendar1.isLenient());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=0,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar1.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar1.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar1.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertFalse(gregorianCalendar1.equals((Object)gregorianCalendar0));
      //  // Unstable assertion: assertNotSame(gregorianCalendar1, gregorianCalendar0);
      
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar1);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(79, person0.getId());
      //  // Unstable assertion: assertTrue(gregorianCalendar1.isLenient());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=0,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar1.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar1.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar1.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertFalse(gregorianCalendar1.equals((Object)gregorianCalendar0));
      //  // Unstable assertion: assertNotSame(gregorianCalendar1, gregorianCalendar0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(78, person0.getId());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar(1971, 0, 1, 0, 0, 0);
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=1971,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals(78, person0.getId());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=1971,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(77, person0.getId());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar(0, 0, 0, 0, 0, 0);
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      
      person0.setDateOfBirth(gregorianCalendar0);
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(77, person0.getId());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      
      GregorianCalendar gregorianCalendar1 = new GregorianCalendar(0, 0, 0, 21, 177, 180);
      //  // Unstable assertion: assertNotNull(gregorianCalendar1);
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=1,HOUR=9,HOUR_OF_DAY=21,MINUTE=177,SECOND=180,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar1.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar1.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar1.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar1.isLenient());
      //  // Unstable assertion: assertFalse(gregorianCalendar1.equals((Object)gregorianCalendar0));
      
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar1);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(77, person0.getId());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=1,HOUR=9,HOUR_OF_DAY=21,MINUTE=177,SECOND=180,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar1.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar1.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar1.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar1.isLenient());
      //  // Unstable assertion: assertFalse(gregorianCalendar1.equals((Object)gregorianCalendar0));
      //  // Unstable assertion: assertNotSame(gregorianCalendar1, gregorianCalendar0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Person person0 = new Person("", "", true);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(74, person0.getId());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      
      Person person1 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person1);
      //  // Unstable assertion: assertFalse(person1.isFemale());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertEquals(0, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertEquals("male", person1.getGender());
      //  // Unstable assertion: assertEquals(75, person1.getId());
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      
      person0.addChild(person1);
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(74, person0.getId());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person1.isFemale());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertEquals(0, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertEquals("male", person1.getGender());
      //  // Unstable assertion: assertEquals(75, person1.getId());
      //  // Unstable assertion: assertFalse(person0.equals((Object)person1));
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      //  // Unstable assertion: assertNotSame(person0, person1);
      //  // Unstable assertion: assertNotSame(person1, person0);
      
      Person person2 = Person.restorePerson(0, "", "", true);
      //  // Unstable assertion: assertNotNull(person2);
      //  // Unstable assertion: assertEquals(1, person2.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person2.getLastName());
      //  // Unstable assertion: assertEquals("female", person2.getGender());
      //  // Unstable assertion: assertEquals("", person2.getFirstName());
      //  // Unstable assertion: assertTrue(person2.isFemale());
      //  // Unstable assertion: assertEquals(0, person2.getId());
      //  // Unstable assertion: assertFalse(person2.equals((Object)person1));
      //  // Unstable assertion: assertFalse(person2.equals((Object)person0));
      //  // Unstable assertion: assertNotSame(person2, person1);
      //  // Unstable assertion: assertNotSame(person2, person0);
      
      person0.addChild(person2);
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(74, person0.getId());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(1, person2.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person2.getLastName());
      //  // Unstable assertion: assertEquals("female", person2.getGender());
      //  // Unstable assertion: assertEquals("", person2.getFirstName());
      //  // Unstable assertion: assertTrue(person2.isFemale());
      //  // Unstable assertion: assertEquals(0, person2.getId());
      //  // Unstable assertion: assertFalse(person0.equals((Object)person2));
      //  // Unstable assertion: assertFalse(person0.equals((Object)person1));
      //  // Unstable assertion: assertFalse(person2.equals((Object)person1));
      //  // Unstable assertion: assertFalse(person2.equals((Object)person0));
      //  // Unstable assertion: assertNotSame(person0, person2);
      //  // Unstable assertion: assertNotSame(person0, person1);
      //  // Unstable assertion: assertNotSame(person2, person1);
      //  // Unstable assertion: assertNotSame(person2, person0);
      
      try { 
        person1.addChild(person2);
       //  fail("Expecting exception: AddRelationException");
       // Unstable assertion
      } catch(AddRelationException e) {
         //
         // Relation exists or is illegal
         //
         verifyException("familytree.model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Person person0 = Person.restorePerson(1, "", "", true);
      assertNotNull(person0);
      assertEquals("", person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertEquals(1, person0.getId());
      assertTrue(person0.isFemale());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      assertNotNull(person0);
      assertEquals("", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertEquals(0, person0.getId());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      
      boolean boolean0 = person0.isFemale();
      assertTrue(boolean0);
      assertEquals("", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertEquals(0, person0.getId());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals(0, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      
      Person person1 = new Person("", "", true);
      //  // Unstable assertion: assertNotNull(person1);
      //  // Unstable assertion: assertEquals(1, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals("female", person1.getGender());
      //  // Unstable assertion: assertEquals(71, person1.getId());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertTrue(person1.isFemale());
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      
      person1.addSpouse(person0);
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals(0, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals(1, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals("female", person1.getGender());
      //  // Unstable assertion: assertEquals(71, person1.getId());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertTrue(person1.isFemale());
      //  // Unstable assertion: assertFalse(person0.equals((Object)person1));
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      //  // Unstable assertion: assertNotSame(person0, person1);
      //  // Unstable assertion: assertNotSame(person1, person0);
      
      Vector vector0 = person1.getRelationships();
      //  // Unstable assertion: assertNotNull(vector0);
      //  // Unstable assertion: assertEquals(1, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals("female", person1.getGender());
      //  // Unstable assertion: assertEquals(71, person1.getId());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertTrue(person1.isFemale());
      //  // Unstable assertion: assertEquals(1, vector0.size());
      //  // Unstable assertion: assertFalse(vector0.isEmpty());
      //  // Unstable assertion: assertEquals(10, vector0.capacity());
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      //  // Unstable assertion: assertNotSame(person1, person0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Person person0 = new Person("", " ", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals(" ", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(69, person0.getId());
      
      String string0 = person0.getLastName();
      //  // Unstable assertion: assertNotNull(string0);
      //  // Unstable assertion: assertEquals(" ", string0);
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals(" ", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(69, person0.getId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(68, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      
      String string0 = person0.getLastName();
      //  // Unstable assertion: assertNotNull(string0);
      //  // Unstable assertion: assertEquals("", string0);
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(68, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(67, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      
      int int0 = person0.getId();
      //  // Unstable assertion: assertEquals(67, int0);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(67, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Person person0 = Person.restorePerson((-1), "", "", false);
      assertNotNull(person0);
      assertEquals("male", person0.getGender());
      assertEquals((-1), person0.getId());
      assertEquals("", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
      
      int int0 = person0.getId();
      assertEquals((-1), int0);
      assertEquals("male", person0.getGender());
      assertEquals((-1), person0.getId());
      assertEquals("", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(65, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      
      person0.setFirstName((String) null);
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(65, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertNull(person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      
      String string0 = person0.getFirstName();
      //  // Unstable assertion: assertNull(string0);
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(65, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertNull(person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "3", "", true);
      assertNotNull(person0);
      assertEquals("3", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertEquals(1, person0.getGenderAsInt());
      assertTrue(person0.isFemale());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      
      String string0 = person0.getFirstName();
      assertNotNull(string0);
      assertEquals("3", string0);
      assertEquals("3", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertEquals(1, person0.getGenderAsInt());
      assertTrue(person0.isFemale());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(63, person0.getId());
      
      person0.setDateOfDeath((GregorianCalendar) null);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(63, person0.getId());
      
      // Undeclared exception!
      try { 
        person0.getDateOfDeath();
       //  fail("Expecting exception: NullPointerException");
       // Unstable assertion
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("familytree.model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(62, person0.getId());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      
      person0.setDateOfBirth((GregorianCalendar) null);
      //  // Unstable assertion: assertEquals(62, person0.getId());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      
      // Undeclared exception!
      try { 
        person0.getDateOfBirth();
       //  fail("Expecting exception: NullPointerException");
       // Unstable assertion
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("familytree.model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(61, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      
      person0.setDateOfDeath((GregorianCalendar) null);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(61, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar(0, 0, 0, 0, 0, 0);
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      
      // Undeclared exception!
      try { 
        person0.dateOfDeathEquals(gregorianCalendar0);
       //  fail("Expecting exception: NullPointerException");
       // Unstable assertion
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("familytree.model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(60, person0.getId());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar(0, 0, 0, 0, 0);
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      
      gregorianCalendar0.setLenient(false);
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=false,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertFalse(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      
      // Undeclared exception!
      try { 
        person0.dateOfBirthEquals(gregorianCalendar0);
       //  fail("Expecting exception: IllegalArgumentException");
       // Unstable assertion
      } catch(IllegalArgumentException e) {
         //
         // YEAR
         //
         verifyException("java.util.GregorianCalendar", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Person person0 = new Person("", "", true);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(59, person0.getId());
      
      // Undeclared exception!
      try { 
        person0.addSpouse((Person) null);
       //  fail("Expecting exception: NullPointerException");
       // Unstable assertion
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("familytree.model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(58, person0.getId());
      
      // Undeclared exception!
      try { 
        person0.addChild((Person) null);
       //  fail("Expecting exception: NullPointerException");
       // Unstable assertion
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("familytree.model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Person person0 = new Person("", "", true);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(56, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      
      Person person1 = new Person("", "", true);
      //  // Unstable assertion: assertNotNull(person1);
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertTrue(person1.isFemale());
      //  // Unstable assertion: assertEquals(1, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertEquals("female", person1.getGender());
      //  // Unstable assertion: assertEquals(57, person1.getId());
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      
      person1.addChild(person0);
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(56, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertTrue(person1.isFemale());
      //  // Unstable assertion: assertEquals(1, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertEquals("female", person1.getGender());
      //  // Unstable assertion: assertEquals(57, person1.getId());
      //  // Unstable assertion: assertFalse(person0.equals((Object)person1));
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      //  // Unstable assertion: assertNotSame(person0, person1);
      //  // Unstable assertion: assertNotSame(person1, person0);
      
      Relation relation0 = person0.getRelation(person1);
      //  // Unstable assertion: assertNotNull(relation0);
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(56, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertTrue(person1.isFemale());
      //  // Unstable assertion: assertEquals(1, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertEquals("female", person1.getGender());
      //  // Unstable assertion: assertEquals(57, person1.getId());
      //  // Unstable assertion: assertFalse(person0.equals((Object)person1));
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      //  // Unstable assertion: assertNotSame(person0, person1);
      //  // Unstable assertion: assertNotSame(person1, person0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Person person0 = new Person("", "", true);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals(54, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      
      Person person1 = new Person("", "", true);
      //  // Unstable assertion: assertNotNull(person1);
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertTrue(person1.isFemale());
      //  // Unstable assertion: assertEquals("female", person1.getGender());
      //  // Unstable assertion: assertEquals(1, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals(55, person1.getId());
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      
      person0.addChild(person1);
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals(54, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person1.getLastName());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
      //  // Unstable assertion: assertTrue(person1.isFemale());
      //  // Unstable assertion: assertEquals("female", person1.getGender());
      //  // Unstable assertion: assertEquals(1, person1.getGenderAsInt());
      //  // Unstable assertion: assertEquals(55, person1.getId());
      //  // Unstable assertion: assertFalse(person0.equals((Object)person1));
      //  // Unstable assertion: assertFalse(person1.equals((Object)person0));
      //  // Unstable assertion: assertNotSame(person0, person1);
      //  // Unstable assertion: assertNotSame(person1, person0);
      
      Relation relation0 = person0.getRelation(person0);
      //  // Unstable assertion: assertNull(relation0);
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals(54, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertFalse(person0.equals((Object)person1));
      //  // Unstable assertion: assertNotSame(person0, person1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(53, person0.getId());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar(124, 1199, 1987, 2016, 0);
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=124,MONTH=1199,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1987,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=2016,HOUR_OF_DAY=2016,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(53, person0.getId());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=124,MONTH=1199,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1987,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=2016,HOUR_OF_DAY=2016,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(52, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar(0, 0, 1, 0, 0, 0);
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(52, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(51, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      
      boolean boolean0 = person0.dateOfDeathEquals((Calendar) null);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals(51, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(50, person0.getId());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar();
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=1539536419158,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2018,MONTH=9,WEEK_OF_YEAR=41,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=287,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=0,SECOND=19,MILLISECOND=158,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals(50, person0.getId());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=1539536419158,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2018,MONTH=9,WEEK_OF_YEAR=41,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=287,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=0,SECOND=19,MILLISECOND=158,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(49, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar(0, 0, 1, 0, 0, 0);
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals(49, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=0,MONTH=0,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(48, person0.getId());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar(124, 1199, 1987, 2016, 0);
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=124,MONTH=1199,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1987,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=2016,HOUR_OF_DAY=2016,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals(48, person0.getId());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=124,MONTH=1199,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1987,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=2016,HOUR_OF_DAY=2016,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Person person0 = new Person("", "", false);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(47, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar();
      //  // Unstable assertion: assertNotNull(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=1539536418886,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2018,MONTH=9,WEEK_OF_YEAR=41,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=287,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=0,SECOND=18,MILLISECOND=886,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      
      gregorianCalendar0.setTimeInMillis(0L);
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=0,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
      
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      //  // Unstable assertion: assertTrue(boolean0);
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("male", person0.getGender());
      //  // Unstable assertion: assertEquals(47, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
      //  // Unstable assertion: assertFalse(person0.isFemale());
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=0,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertEquals(2, gregorianCalendar0.getFirstDayOfWeek());
      //  // Unstable assertion: assertEquals(4, gregorianCalendar0.getMinimalDaysInFirstWeek());
      //  // Unstable assertion: assertTrue(gregorianCalendar0.isLenient());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Person person0 = new Person("", "", true);
      //  // Unstable assertion: assertNotNull(person0);
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals(46, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
      
      boolean boolean0 = person0.dateOfBirthEquals((Calendar) null);
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
      //  // Unstable assertion: assertEquals("", person0.getFirstName());
      //  // Unstable assertion: assertTrue(person0.isFemale());
      //  // Unstable assertion: assertEquals(46, person0.getId());
      //  // Unstable assertion: assertEquals("", person0.getLastName());
      //  // Unstable assertion: assertEquals("female", person0.getGender());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Person person0 = new Person("", "", false);
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar();
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=1539536415891,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2018,MONTH=9,WEEK_OF_YEAR=41,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=287,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=0,SECOND=15,MILLISECOND=891,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Person person0 = new Person("", "", true);
      int int0 = person0.getGenderAsInt();
      //  // Unstable assertion: assertEquals(11, person0.getId());
      //  // Unstable assertion: assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Person person0 = new Person("", "", false);
      int int0 = person0.getGenderAsInt();
      //  // Unstable assertion: assertEquals(3, person0.getId());
      //  // Unstable assertion: assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      String string0 = person0.getGender();
      assertEquals("", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertEquals(0, person0.getId());
      assertEquals("female", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", false);
      String string0 = person0.getGender();
      assertEquals("", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertEquals("male", string0);
      assertEquals(0, person0.getId());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Person person0 = new Person("", "", false);
      Person person1 = new Person("", "", false);
      person0.addChild(person1);
      person0.getChildren();
      //  // Unstable assertion: assertEquals(25, person0.getId());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      Person person1 = new Person("", "", true);
      person0.addSpouse(person1);
      person1.getChildren();
      //  // Unstable assertion: assertEquals(34, person1.getId());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      Person person1 = new Person("", "", true);
      person1.addSpouse(person0);
      //  // Unstable assertion: assertEquals(68, person1.getId());
      
      person0.getRelation(person0);
      //  // Unstable assertion: assertEquals("", person0.getLastName());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      Person person1 = new Person("", "", true);
      person0.addSpouse(person1);
      //  // Unstable assertion: assertEquals(30, person1.getId());
      
      boolean boolean0 = person0.removeRelation(person0);
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Person person0 = new Person("", "", false);
      Person person1 = new Person("", "", false);
      person1.addChild(person0);
      person1.getRelation(person0);
      //  // Unstable assertion: assertEquals(20, person1.getId());
      //  // Unstable assertion: assertEquals("", person1.getFirstName());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, false);
      Person person1 = new Person("", "", false);
      Person person2 = new Person("", "", true);
      person0.addChild(person2);
      person1.addSpouse(person2);
      //  // Unstable assertion: assertEquals(49, person2.getId());
      //  // Unstable assertion: assertEquals(48, person1.getId());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, false);
      Person person1 = new Person("", "", false);
      person0.addSpouse(person1);
      Person person2 = Person.restorePerson(0, "", "", false);
      person1.addSpouse(person2);
      //  // Unstable assertion: assertEquals((-70), person1.getId());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, false);
      Person person1 = new Person("", "", false);
      person0.addSpouse(person1);
      Person person2 = new Person("", "", true);
      person0.addChild(person2);
      person1.addSpouse(person2);
      //  // Unstable assertion: assertEquals(14, person1.getId());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, false);
      Person person1 = new Person("", "", false);
      person0.addSpouse(person1);
      try { 
        person0.addChild(person1);
        fail("Expecting exception: AddRelationException");
      
      } catch(AddRelationException e) {
         //
         // Relation exists or is illegal
         //
         verifyException("familytree.model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      try { 
        person0.addSpouse(person0);
        fail("Expecting exception: AddRelationException");
      
      } catch(AddRelationException e) {
         //
         // Relation exists or is illegal
         //
         verifyException("familytree.model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", false);
      int int0 = person0.getId();
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
      assertEquals(0, int0);
      assertEquals("", person0.getFirstName());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      String string0 = person0.getFirstName();
      assertEquals("", string0);
      assertEquals("", person0.getLastName());
      assertTrue(person0.isFemale());
      assertEquals(0, person0.getId());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Person person0 = new Person("", "", false);
      GregorianCalendar gregorianCalendar0 = person0.getDateOfDeath();
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      //  // Unstable assertion: assertEquals(41, person0.getId());
      //  // Unstable assertion: assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Person person0 = new Person("", "", false);
      Person person1 = new Person("", "", false);
      person1.addChild(person0);
      boolean boolean0 = person0.removeRelation(person1);
      //  // Unstable assertion: assertTrue(boolean0);
      //  // Unstable assertion: assertEquals(11, person0.getId());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Person person0 = new Person("", "", false);
      person0.toString();
      //  // Unstable assertion: assertEquals(3, person0.getId());
      //  // Unstable assertion: assertEquals(0, person0.getGenderAsInt());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Person person0 = new Person("", "", false);
      person0.setFemale(true);
      //  // Unstable assertion: assertEquals((-4), person0.getId());
      //  // Unstable assertion: assertEquals(1, person0.getGenderAsInt());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Person person0 = new Person("", "", false);
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      //  // Unstable assertion: assertEquals((-8), person0.getId());
      //  // Unstable assertion: assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Person person0 = new Person("", "", false);
      person0.getRelationships();
      //  // Unstable assertion: assertEquals(1, person0.getId());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, false);
      person0.getLastName();
      //  // Unstable assertion: assertEquals(7, person0.getId());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Person person0 = new Person("", "", false);
      person0.setLastName("");
      //  // Unstable assertion: assertEquals(46, person0.getId());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Person person0 = new Person("", "", false);
      GregorianCalendar gregorianCalendar0 = new GregorianCalendar();
      person0.setDateOfDeath(gregorianCalendar0);
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      //  // Unstable assertion: assertEquals("java.util.GregorianCalendar[time=1539536399192,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2018,MONTH=9,WEEK_OF_YEAR=41,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=287,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=4,HOUR_OF_DAY=16,MINUTE=59,SECOND=59,MILLISECOND=192,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      //  // Unstable assertion: assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Person person0 = new Person("", "", false);
      boolean boolean0 = person0.isFemale();
      //  // Unstable assertion: assertEquals(1, person0.getId());
      //  // Unstable assertion: assertFalse(boolean0);
  }
}
